import {
  Title,
  Gender,
  Orientation,
  TherapistType,
  AreaOfFocus,
  ClinicalApproach,
  GoverningBody,
  MembershipLevel,
  SpokenLanguageCode,
  LanguageProficiency,
  SessionType
} from "../types/enums";

export const titleLabels: Record<Title, string> = {
  [Title.NotSpecified]: "Not Specified",
  [Title.Mr]: "Mr",
  [Title.Mrs]: "Mrs",
  [Title.Miss]: "Miss",
  [Title.Ms]: "Ms",
  [Title.Mx]: "Mx",
  [Title.Dr]: "Dr",
  [Title.Prof]: "Prof",
  [Title.Rev]: "Rev",
  [Title.Sir]: "Sir",
  [Title.Lady]: "Lady",
  [Title.Lord]: "Lord",
  [Title.Dame]: "Dame",
  [Title.Other]: "Other"
};

export const genderLabels: Record<Gender, string> = {
  [Gender.NotSpecified]: "Not Specified",
  [Gender.Male]: "Male",
  [Gender.Female]: "Female",
  [Gender.NonBinary]: "Non-Binary",
  [Gender.PreferNotToSay]: "Prefer Not to Say",
  [Gender.Other]: "Other"
};

export const orientationLabels: Record<Orientation, string> = {
  [Orientation.NotSpecified]: "Not Specified",
  [Orientation.Straight]: "Straight",
  [Orientation.Gay]: "Gay",
  [Orientation.Lesbian]: "Lesbian",
  [Orientation.Bisexual]: "Bisexual",
  [Orientation.Pansexual]: "Pansexual",
  [Orientation.Asexual]: "Asexual",
  [Orientation.Queer]: "Queer",
  [Orientation.PreferNotToSay]: "Prefer Not to Say",
  [Orientation.Other]: "Other"
};

export const therapistTypeLabels: Record<TherapistType, string> = {
  [TherapistType.CON]: "Conservative",
  [TherapistType.LIB]: "Liberal",
  [TherapistType.NRG]: "Non-Religious",
  [TherapistType.CHR]: "Christian",
  [TherapistType.MUS]: "Muslim",
  [TherapistType.HIN]: "Hindu",
  [TherapistType.JUD]: "Jewish",
  [TherapistType.BUD]: "Buddhist",
  [TherapistType.POC]: "Person of Color",
  [TherapistType.OLD]: "Older Adult",
  [TherapistType.LGB]: "LGBTQ+"
};

export const areaOfFocusLabels: Record<AreaOfFocus, string> = {
  [AreaOfFocus.ABD]: "Abandonment Issues",
  [AreaOfFocus.ADD]: "Attention Deficit Disorder",
  [AreaOfFocus.ADH]: "ADHD",
  [AreaOfFocus.AFC]: "Adoption and Foster Care",
  [AreaOfFocus.AGI]: "Aging Issues",
  [AreaOfFocus.AGR]: "Anger Management",
  [AreaOfFocus.ASD]: "Autism Spectrum Disorder",
  [AreaOfFocus.ASP]: "Antisocial Personality",
  [AreaOfFocus.ATC]: "Attachment Issues",
  [AreaOfFocus.AVP]: "Avoidant Personality",
  [AreaOfFocus.AX]: "Anxiety",
  [AreaOfFocus.BDSM]: "BDSM and Kink",
  [AreaOfFocus.BDI]: "Body Image",
  [AreaOfFocus.BFI]: "Blended Families",
  [AreaOfFocus.BIP]: "Bipolar Disorder",
  [AreaOfFocus.BOR]: "Borderline Personality",
  [AreaOfFocus.BUR]: "Burnout",
  [AreaOfFocus.CAN]: "Cancer",
  [AreaOfFocus.CI]: "Commitment Issues",
  [AreaOfFocus.CIS]: "Caregiver Issues",
  [AreaOfFocus.CMD]: "Co-morbidity",
  [AreaOfFocus.CNT]: "Control",
  [AreaOfFocus.CD]: "Codependency",
  [AreaOfFocus.CP]: "Communication Problems",
  [AreaOfFocus.CPI]: "Chronic Pain / Illness",
  [AreaOfFocus.CWD]: "Coping with Disaster",
  [AreaOfFocus.DBT]: "Disabilities",
  [AreaOfFocus.DEP]: "Depression",
  [AreaOfFocus.DIS]: "Dissociative Disorders",
  [AreaOfFocus.DMDD]: "Disruptive Mood Dysregulation",
  [AreaOfFocus.DP]: "Dependent Personality",
  [AreaOfFocus.DV]: "Domestic Violence",
  [AreaOfFocus.DVS]: "Divorce / Separation",
  [AreaOfFocus.EFD]: "Eating Disorders",
  [AreaOfFocus.EMP]: "Emptiness / Apathy",
  [AreaOfFocus.EOL]: "End of Life Issues",
  [AreaOfFocus.ESI]: "Emergency Services Issues",
  [AreaOfFocus.FAM]: "Family Issues",
  [AreaOfFocus.FGV]: "Forgiveness",
  [AreaOfFocus.FHD]: "Fatherhood Issues",
  [AreaOfFocus.FRT]: "Fertility and Reproductive",
  [AreaOfFocus.GID]: "Gender Identity",
  [AreaOfFocus.GRF]: "Grief and Loss",
  [AreaOfFocus.GS]: "Guilt / Shame",
  [AreaOfFocus.HI]: "Hearing Impairment",
  [AreaOfFocus.HIV]: "HIV/AIDS",
  [AreaOfFocus.HRD]: "Hoarding Disorder",
  [AreaOfFocus.IL]: "Isolation / Loneliness",
  [AreaOfFocus.IMG]: "Immigration Issues",
  [AreaOfFocus.IMP]: "Impulsivity",
  [AreaOfFocus.INF]: "Infidelity",
  [AreaOfFocus.INS]: "Insomnia / Sleep Disorders",
  [AreaOfFocus.INT]: "Internet/Technology Addiction",
  [AreaOfFocus.JLY]: "Jealousy",
  [AreaOfFocus.LDI]: "Learning Disabilities",
  [AreaOfFocus.LGB]: "LGBTQ+ Issues",
  [AreaOfFocus.LP]: "Life Purpose",
  [AreaOfFocus.MCC]: "Multi Cultural Concerns",
  [AreaOfFocus.MD]: "Mood Disorders",
  [AreaOfFocus.MFI]: "Money / Financial Issues",
  [AreaOfFocus.MHD]: "Motherhood Issues",
  [AreaOfFocus.MI]: "Men's Issues",
  [AreaOfFocus.MLC]: "Mid Life Crisis",
  [AreaOfFocus.NRC]: "Narcissism",
  [AreaOfFocus.NSA]: "Non-Substance Addiction",
  [AreaOfFocus.OCD]: "OCD",
  [AreaOfFocus.OPD]: "Oppositional Defiant Disorder",
  [AreaOfFocus.PAR]: "Parenting Issues",
  [AreaOfFocus.PCB]: "Pregnancy / Childbirth",
  [AreaOfFocus.PD]: "Personality Disorders",
  [AreaOfFocus.PER]: "Perfectionism",
  [AreaOfFocus.PH]: "Phobias",
  [AreaOfFocus.PNC]: "Panic Disorder",
  [AreaOfFocus.PNMR]: "Polyamory / Non-Monogamous",
  [AreaOfFocus.PPD]: "Postpartum Depression",
  [AreaOfFocus.PRN]: "Paranoia",
  [AreaOfFocus.PTS]: "PTSD",
  [AreaOfFocus.REL]: "Relationship Issues",
  [AreaOfFocus.SA]: "Substance Abuse / Addiction",
  [AreaOfFocus.SAD]: "Seasonal Affective Disorder",
  [AreaOfFocus.SCH]: "Schizophrenia",
  [AreaOfFocus.SE]: "Self-Esteem",
  [AreaOfFocus.SEX]: "Sexual Issues",
  [AreaOfFocus.SH]: "Self-Harm",
  [AreaOfFocus.SL]: "Self-Love",
  [AreaOfFocus.SOC]: "Social Anxiety",
  [AreaOfFocus.SOM]: "Somatization Disorder",
  [AreaOfFocus.STR]: "Stress Management",
  [AreaOfFocus.SUP]: "Support Groups",
  [AreaOfFocus.SVC]: "Smoking / Vaping Cessation",
  [AreaOfFocus.SXD]: "Sexual Dysfunction",
  [AreaOfFocus.SXI]: "Sexual Identity",
  [AreaOfFocus.TBI]: "Traumatic Brain Injury",
  [AreaOfFocus.TIC]: "Tic Disorders",
  [AreaOfFocus.TRA]: "Trauma",
  [AreaOfFocus.TRI]: "Trichotillomania",
  [AreaOfFocus.VAI]: "Veteran and Armed Forces",
  [AreaOfFocus.VI]: "Visual Impairment",
  [AreaOfFocus.WOI]: "Women's Issues",
  [AreaOfFocus.WPI]: "Work / Professional Issues",
  [AreaOfFocus.YAI]: "Youth and Adolescents",
  [AreaOfFocus.SPT]: "Spiritual Therapy",
  [AreaOfFocus.RLT]: "Religious Therapy",
  [AreaOfFocus.BEM]: "Black and Ethnic Minority",
};

export const sessionTypeLabels: Record<SessionType, string> = {
  [SessionType.Counselling]: "Counselling",
  [SessionType.Psychotherapy]: "Psychotherapy",
  [SessionType.Couples]: "Couples",
  [SessionType.Group]: "Group",
  [SessionType.Family]: "Family",
  [SessionType.Supervision]: "Supervision",
};

export const clinicalApproachLabels: Record<ClinicalApproach, string> = {
  [ClinicalApproach.ABT]: "Attachment-Based Therapy",
  [ClinicalApproach.ACT]: "Acceptance and Commitment Therapy",
  [ClinicalApproach.AT]: "Art Therapy",
  [ClinicalApproach.BT]: "Behavioral Therapy",
  [ClinicalApproach.CBT]: "Cognitive Behavioral Therapy (CBT)",
  [ClinicalApproach.CCT]: "Client-Centered Therapy",
  [ClinicalApproach.DBT]: "Dialectical Behavior Therapy (DBT)",
  [ClinicalApproach.EFT]: "Emotionally Focused Therapy",
  [ClinicalApproach.EMDR]: "EMDR",
  [ClinicalApproach.EXT]: "Existential Therapy",
  [ClinicalApproach.GMM]: "Gottman Method",
  [ClinicalApproach.GT]: "Gestalt Therapy",
  [ClinicalApproach.HT]: "Humanistic Therapy",
  [ClinicalApproach.HYP]: "Hypnotherapy",
  [ClinicalApproach.IFST]: "Internal Family Systems",
  [ClinicalApproach.IPT]: "Interpersonal Therapy",
  [ClinicalApproach.IRT]: "Imago Relationship Therapy",
  [ClinicalApproach.IT]: "Integrative Therapy",
  [ClinicalApproach.JT]: "Jungian Therapy",
  [ClinicalApproach.MIT]: "Mindfulness-Based Interventions",
  [ClinicalApproach.MOI]: "Motivational Interviewing",
  [ClinicalApproach.NAT]: "Narrative Therapy",
  [ClinicalApproach.PDT]: "Psychodynamic Therapy",
  [ClinicalApproach.PSA]: "Psychoanalytic Therapy",
  [ClinicalApproach.PT]: "Play Therapy",
  [ClinicalApproach.RT]: "Reality Therapy",
  [ClinicalApproach.SFT]: "Solution-Focused Therapy",
  [ClinicalApproach.SMT]: "Somatic Therapy",
  [ClinicalApproach.SYT]: "Systemic Therapy",
  [ClinicalApproach.TFT]: "Trauma-Focused Therapy"
};

export const governingBodyLabels: Record<GoverningBody, string> = {
  [GoverningBody.BACP]: "BACP (UK)",
  [GoverningBody.UKCP]: "UKCP (UK)",
  [GoverningBody.HCPC]: "HCPC (UK)",
  [GoverningBody.BPS]: "BPS (UK)",
  [GoverningBody.NCPS]: "NCPS (UK)",
  [GoverningBody.COSCA]: "COSCA (Scotland)",
  [GoverningBody.APA]: "APA (USA)",
  [GoverningBody.ACA]: "ACA (USA)",
  [GoverningBody.AAMFT]: "AAMFT (USA)",
  [GoverningBody.NASW]: "NASW (USA)",
  [GoverningBody.NBCC]: "NBCC (USA)",
  [GoverningBody.ABPP]: "ABPP (USA)",
  [GoverningBody.ABCT]: "ABCT (USA)",
  [GoverningBody.ADAA]: "ADAA (USA)",
  [GoverningBody.CPA]: "CPA (Canada)",
  [GoverningBody.CCPA]: "CCPA (Canada)",
  [GoverningBody.CASW]: "CASW (Canada)",
  [GoverningBody.CRPO]: "CRPO (Canada)",
  [GoverningBody.CPBC]: "CPBC (Canada)",
  [GoverningBody.APS]: "APS (Australia)",
  [GoverningBody.PACFA]: "PACFA (Australia)",
  [GoverningBody.AASW]: "AASW (Australia)",
  [GoverningBody.AHPRA]: "AHPRA (Australia)",
  [GoverningBody.NZPS]: "NZPS (New Zealand)",
  [GoverningBody.NZAC]: "NZAC (New Zealand)",
  [GoverningBody.NZAP]: "NZAP (New Zealand)",
  [GoverningBody.PSI]: "PSI (Ireland)",
  [GoverningBody.IACP]: "IACP (Ireland)",
  [GoverningBody.IAHIP]: "IAHIP (Ireland)",
  [GoverningBody.EAP]: "EAP (Europe)",
  [GoverningBody.EFPA]: "EFPA (Europe)",
  [GoverningBody.EAC]: "EAC (Europe)",
  [GoverningBody.BDP]: "BDP (Germany)",
  [GoverningBody.DGTV]: "DGTV (Germany)",
  [GoverningBody.SFP]: "SFP (France)",
  [GoverningBody.SNPPsy]: "SNPPsy (France)",
  [GoverningBody.NIP]: "NIP (Netherlands)",
  [GoverningBody.VGCt]: "VGCt (Netherlands)",
  [GoverningBody.FSP]: "FSP (Switzerland)",
  [GoverningBody.SBAP]: "SBAP (Switzerland)",
  [GoverningBody.OPL]: "OPL (Italy)",
  [GoverningBody.CNOP]: "CNOP (Italy)",
  [GoverningBody.COP]: "COP (Spain)",
  [GoverningBody.NPF]: "NPF (Norway)",
  [GoverningBody.SPR]: "SPR (Sweden)",
  [GoverningBody.DP]: "DP (Denmark)",
  [GoverningBody.JPA]: "JPA (Japan)",
  [GoverningBody.PsySSA]: "PsySSA (South Africa)",
  [GoverningBody.HPCSA]: "HPCSA (South Africa)",
  [GoverningBody.IUPsyS]: "IUPsyS (International)",
  [GoverningBody.WCP]: "WCP (International)",
  [GoverningBody.IAAP]: "IAAP (International)",
  [GoverningBody.Other]: "Other",
  [GoverningBody.NotApplicable]: "Not Applicable"
};

export const membershipLevelLabels: Record<MembershipLevel, string> = {
  [MembershipLevel.BACPRegistered]: "BACP Registered",
  [MembershipLevel.BACPAccredited]: "BACP Accredited",
  [MembershipLevel.BACPSeniorAccredited]: "BACP Senior Accredited",
  [MembershipLevel.UKCPRegistered]: "UKCP Registered",
  [MembershipLevel.UKCPAccredited]: "UKCP Accredited",
  [MembershipLevel.UKCPSenior]: "UKCP Senior",
  [MembershipLevel.BPSStudent]: "BPS Student",
  [MembershipLevel.BPSGraduate]: "BPS Graduate",
  [MembershipLevel.BPSChartered]: "BPS Chartered",
  [MembershipLevel.BPSFellow]: "BPS Fellow",
  [MembershipLevel.HCPCRegistered]: "HCPC Registered",
  [MembershipLevel.NCPSMember]: "NCPS Member",
  [MembershipLevel.NCPSAccredited]: "NCPS Accredited",
  [MembershipLevel.COSCAMember]: "COSCA Member",
  [MembershipLevel.COSCAAccredited]: "COSCA Accredited",
  [MembershipLevel.APAStudent]: "APA Student",
  [MembershipLevel.APAMember]: "APA Member",
  [MembershipLevel.APAFellow]: "APA Fellow",
  [MembershipLevel.APADiplomate]: "APA Diplomate",
  [MembershipLevel.ACAStudent]: "ACA Student",
  [MembershipLevel.ACARegular]: "ACA Regular",
  [MembershipLevel.ACAProfessional]: "ACA Professional",
  [MembershipLevel.AAMFTStudent]: "AAMFT Student",
  [MembershipLevel.AAMFTAssociate]: "AAMFT Associate",
  [MembershipLevel.AAMFTClinical]: "AAMFT Clinical",
  [MembershipLevel.AAMFTApproved]: "AAMFT Approved",
  [MembershipLevel.NASWStudent]: "NASW Student",
  [MembershipLevel.NASWRegular]: "NASW Regular",
  [MembershipLevel.NASWQualified]: "NASW Qualified",
  [MembershipLevel.NBCCCertified]: "NBCC Certified",
  [MembershipLevel.CPAStudent]: "CPA Student",
  [MembershipLevel.CPARegular]: "CPA Regular",
  [MembershipLevel.CPAFellow]: "CPA Fellow",
  [MembershipLevel.CCPAStudent]: "CCPA Student",
  [MembershipLevel.CCPARegular]: "CCPA Regular",
  [MembershipLevel.CCPACertified]: "CCPA Certified",
  [MembershipLevel.CRPORegistered]: "CRPO Registered",
  [MembershipLevel.APSStudent]: "APS Student",
  [MembershipLevel.APSAssociate]: "APS Associate",
  [MembershipLevel.APSMember]: "APS Member",
  [MembershipLevel.APSFellow]: "APS Fellow",
  [MembershipLevel.PACFARegistrar]: "PACFA Registrar",
  [MembershipLevel.PACFAClinical]: "PACFA Clinical",
  [MembershipLevel.AHPRAGeneral]: "AHPRA General",
  [MembershipLevel.AHPRASpecialist]: "AHPRA Specialist",
  [MembershipLevel.NZPSStudent]: "NZPS Student",
  [MembershipLevel.NZPSAssociate]: "NZPS Associate",
  [MembershipLevel.NZPSMember]: "NZPS Member",
  [MembershipLevel.NZPSFellow]: "NZPS Fellow",
  [MembershipLevel.NZACProvisional]: "NZAC Provisional",
  [MembershipLevel.NZACMember]: "NZAC Member",
  [MembershipLevel.PSIStudent]: "PSI Student",
  [MembershipLevel.PSIAssociate]: "PSI Associate",
  [MembershipLevel.PSIMember]: "PSI Member",
  [MembershipLevel.PSIFellow]: "PSI Fellow",
  [MembershipLevel.IACPStudent]: "IACP Student",
  [MembershipLevel.IACPMember]: "IACP Member",
  [MembershipLevel.IACPAccredited]: "IACP Accredited",
  [MembershipLevel.EAPMember]: "EAP Member",
  [MembershipLevel.EAPCertified]: "EAP Certified",
  [MembershipLevel.Student]: "Student",
  [MembershipLevel.Trainee]: "Trainee",
  [MembershipLevel.Associate]: "Associate",
  [MembershipLevel.Member]: "Member",
  [MembershipLevel.Regular]: "Regular",
  [MembershipLevel.Professional]: "Professional",
  [MembershipLevel.Senior]: "Senior",
  [MembershipLevel.Fellow]: "Fellow",
  [MembershipLevel.Accredited]: "Accredited",
  [MembershipLevel.Registered]: "Registered",
  [MembershipLevel.Licensed]: "Licensed",
  [MembershipLevel.Certified]: "Certified",
  [MembershipLevel.Chartered]: "Chartered",
  [MembershipLevel.Other]: "Other"
};

export const languageLabels: Record<SpokenLanguageCode, string> = {
  [SpokenLanguageCode.EN]: "English",
  [SpokenLanguageCode.ES]: "Spanish",
  [SpokenLanguageCode.FR]: "French",
  [SpokenLanguageCode.DE]: "German",
  [SpokenLanguageCode.IT]: "Italian",
  [SpokenLanguageCode.PT]: "Portuguese",
  [SpokenLanguageCode.RU]: "Russian",
  [SpokenLanguageCode.ZH]: "Chinese (Mandarin)",
  [SpokenLanguageCode.JA]: "Japanese",
  [SpokenLanguageCode.KO]: "Korean",
  [SpokenLanguageCode.AR]: "Arabic",
  [SpokenLanguageCode.HI]: "Hindi",
  [SpokenLanguageCode.TR]: "Turkish",
  [SpokenLanguageCode.PL]: "Polish",
  [SpokenLanguageCode.NL]: "Dutch",
  [SpokenLanguageCode.SV]: "Swedish",
  [SpokenLanguageCode.NO]: "Norwegian",
  [SpokenLanguageCode.DA]: "Danish",
  [SpokenLanguageCode.FI]: "Finnish",
  [SpokenLanguageCode.EL]: "Greek",
  [SpokenLanguageCode.HE]: "Hebrew",
  [SpokenLanguageCode.UR]: "Urdu",
  [SpokenLanguageCode.FA]: "Persian (Farsi)",
  [SpokenLanguageCode.VI]: "Vietnamese",
  [SpokenLanguageCode.TH]: "Thai"
};

export const proficiencyLabels: Record<LanguageProficiency, string> = {
  [LanguageProficiency.NotSpecified]: "Not Specified",
  [LanguageProficiency.Native]: "Native",
  [LanguageProficiency.Fluent]: "Fluent",
  [LanguageProficiency.Conversational]: "Conversational",
  [LanguageProficiency.Basic]: "Basic",
  [LanguageProficiency.None]: "None"
};