// ============================================================
// Backward-compat re-export — use './shared/types', './client/types',
// or './therapist/types' directly for new code.
// ============================================================

// ---- Shared DTOs ------------------------------------------------------------
export type {
  LoginRequest,
  RegisterRequest,
  AuthResponse,
  CreateConnectionRequest,
  UpdateConnectionRequest,
  ListConnectionsParams,
  SendMessageRequest,
  ListMessagesParams,
  MarkMessagesReadRequest,
  CreateVideoSessionRequest,
  UpdateVideoSessionRequest,
  ListVideoSessionsParams,
  UpdateThemeSettingsRequest,
} from './shared/types';

// ---- Client DTOs ------------------------------------------------------------
export type {
  UpdateClientProfileRequest,
  ListClientsParams,
  FollowTherapistRequest,
  UnfollowTherapistRequest,
  CreateJournalEntryRequest,
  ListJournalEntriesParams,
  UpdateJournalSharingRequest,
  CreateAssessmentRequest,
  ListAssessmentsParams,
  CreateClientNoteRequest,
  ListClientNotesParams,
  PurchaseCourseRequest,
  ListCourseBookingsParams,
} from './client/types';

// ---- Therapist DTOs ---------------------------------------------------------
export type {
  UpdateTherapistProfileRequest,
  UpdateTherapistExtendedProfileRequest,
  ListTherapistsParams,
  CreateSessionRateRequest,
  UpdateSessionRateRequest,
  UpdateAvailabilityRequest,
  CreateWorkshopRequest,
  UpdateWorkshopRequest,
  RegisterWorkshopRequest,
  ListWorkshopsParams,
  CreatePostRequest,
  UpdatePostRequest,
  ToggleLikeRequest,
  ListPostsParams,
  CreateSessionNoteRequest,
  UpdateSessionNoteRequest,
  ListSessionNotesParams,
  CreateTherapistJournalEntryRequest,
  UpdateTherapistJournalEntryRequest,
  ListTherapistJournalEntriesParams,
  CreateCpdEntryRequest,
  UpdateCpdEntryRequest,
  ListCpdEntriesParams,
  CreateSupervisionConnectionRequest,
  UpdateSupervisionConnectionRequest,
  ListSupervisionConnectionsParams,
  CreateSupervisionSessionRequest,
  UpdateSupervisionSessionRequest,
  ListSupervisionSessionsParams,
  CreateBookmarkRequest,
  UpdateBookmarkRequest,
  ListBookmarksParams,
  CreateCoursePackageRequest,
  UpdateCoursePackageRequest,
  ListCoursePackagesParams,
  CreateProBonoTokenRequest,
  ListProBonoTokensParams,
  UseProBonoTokenRequest,
} from './therapist/types';
