export enum AreaOfFocus {
  ABD = 0, // Abandonment Issues
  ADD = 1, // Attention Deficit Disorder
  ADH = 2, // ADHD (Attention Deficit Hyperactivity Disorder)
  AFC = 3, // Adoption and Foster Care Issues
  AGI = 4, // Aging Issues
  AGR = 5, // Anger Management
  ASD = 6, // Autism Spectrum Disorder
  ASP = 7, // Antisocial Personality Disorder
  ATC = 8, // Attachment issues
  AVP = 9, // Avoidant Personality Disorder
  AX = 10, // Anxiety
  BDSM = 11, // BDSM and Kink
  BDI = 12, // Body Image
  BFI = 13, // Blended Families Issues
  BIP = 14, // Bipolar Disorder
  BOR = 15, // Borderline Personality Disorder
  BUR = 16, // Burnout
  CAN = 17, // Cancer
  CI = 18, // Commitment Issues
  CIS = 19, // Caregiver Issues
  CMD = 20, // Co-morbidity
  CNT = 21, // Control
  CD = 22, // Codependency
  CP = 23, // Communication Problems
  CPI = 24, // Chronic Pain / Illness
  CWD = 25, // Coping with disaster
  DBT = 26, // Disabilities
  DEP = 27, // Depression
  DIS = 28, // Dissociative Disorders
  DMDD = 29, // Disruptive Mood Dysregulation Disorder
  DP = 30, // Dependant Personality Disorder
  DV = 31, // Domestic Violence
  DVS = 32, // Divorce / Separation
  EFD = 33, // Eating Disorders
  EMP = 34, // Emptiness / Apathy
  EOL = 35, // End of Life Issues
  ESI = 36, // Emergency Services Issues
  FAM = 37, // Family Issues
  FGV = 38, // Forgiveness
  FHD = 39, // Fatherhood Issues
  FRT = 40, // Fertility and Reproductive Issues
  GID = 41, // Gender Identity Disorder
  GRF = 42, // Grief and Loss
  GS = 43, // Guilt / Shame
  HI = 44, // Hearing Impairment
  HIV = 45, // HIV/AIDS
  HRD = 46, // Hoarding Disorder
  IL = 47, // Isolation / Loneliness
  IMG = 48, // Immigration Issues
  IMP = 49, // Impulsivity
  INF = 50, // Infidelity
  INS = 51, // Insomnia / Sleep Disorders
  INT = 52, // Internet/Technology Addiction
  JLY = 53, // Jealousy
  LDI = 54, // Learning Disabilities
  LGB = 55, // LGBTQ+ Issues
  LP = 56, // Life Purpose
  MCC = 57, // Multi Cultural Concerns
  MD = 58, // Mood Disorders
  MFI = 59, // Money / Financial Issues
  MHD = 60, // Motherhood Issues
  MI = 61, // Mens Issues
  MLC = 62, // Mid Life Crisis
  NRC = 63, // Narcissism
  NSA = 64, // Non substance Addiction
  OCD = 65, // Obsessive Compulsive Disorder
  OPD = 66, // Oppositional Defiant Disorder
  PAR = 67, // Parenting Issues
  PCB = 68, // Pregnancy / Childbirth
  PD = 69, // Personality Disorders
  PER = 70, // Perfectionism
  PH = 71, // Phobias
  PNC = 72, // Panic Disorder and Panic Attacks
  PNMR = 73, // Polyamory / Non-Monogamous Relationships
  PPD = 74, // Postpartum Depression
  PRN = 75, // Paranoia
  PTS = 76, // Post-Traumatic Stress Disorder
  REL = 77, // Relationship Issues
  SA = 78, // Substance Abuse / Addiction
  SAD = 79, // Seasonal Affective Disorder
  SCH = 80, // Schizophrenia
  SE = 81, // Self-Esteem
  SEX = 82, // Sexual Issues
  SH = 83, // Self-Harm
  SL = 84, // Self-Love
  SOC = 85, // Social Anxiety
  SOM = 86, // Somatization Disorder
  STR = 87, // Stress Management
  SUP = 88, // Support Groups
  SVC = 89, // Smoking / Vaping Cessation
  SXD = 90, // Sexual Dysfunction
  SXI = 91, // Sexual Identity
  TBI = 92, // Traumatic Brain Injury
  TIC = 93, // Tic Disorders
  TRA = 94, // Trauma (general)
  TRI = 95, // Trichotillomania
  VAI = 96, // Veteran and Armed Forces Issues
  VI = 97, // Visual Impairment
  WOI = 98, // Womens Issues
  WPI = 99, // Work / Professional Issues
  YAI = 100, // Youth and Adolescents
  SPT = 101, // Spiritual Therapy
  RLT = 102, // Religious Therapy
  BEM = 103, // Black and Ethnic Minority
}
